resources:
  - name: sample_job1
    type: gitRepo
    repoPath: bindushree16/c7node
    configuration:
      integrationName: bindu_github
      branches:
        only: master
    initialVersion:
      sha: master
      
pipelines:
  - name: pipeline121
    steps:
      - name: testpipelines
        type: bash
        setup:
          runtime:            
            type: image
            image:
#               auto:
#                 language: nodejs
#                 versions: 
#                   - 10.15.3
              custom:
                name: drydock/c7node
                tag: master
                options: "--env Villa=good"    
#         configuration:
#           chronological: false 
#           priority: 2
        triggeredBy:
          resources:
            - sample_job1
        execution:
          onExecute:
            - docker pull drydock/c7node:master
            - docker images
            - printenv
            - openssl version
            - openssl genrsa -out key.pem 1024
            
            
      - name: testpipel
        type: bash 
        triggeredBy:
          steps:
            - testpipelines
        execution:
          onExecute:
            - echo "hi"
            - node --version
